[dependencies]
lazy_static = "1.4.0"
base64 = "0.12.0"
reactive_crypto = { git = "https://github.com/gianlu33/rust-sgx-libs.git" }
reactive_net = { git = "https://github.com/gianlu33/rust-sgx-libs.git" }

[features]

debug_prints = []
