[dependencies]
lazy_static = "1.4.0"
base64 = "0.12.0"
threadpool = "1.8.1"
reactive_crypto = { git = "https://github.com/AuthenticExecution/rust-sgx-libs.git" }
reactive_net = { git = "https://github.com/AuthenticExecution/rust-sgx-libs.git" }

[features]
debug_prints = []
measure_time = []
