name: Pypi
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch: # Allow manual triggering
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    -
      uses: actions/checkout@master
    -
      name: code-check
      run: |
        sudo apt update && sudo apt install pylint
        pip install -r requirements.txt
        cd ..
        pylint rust-sgx-gen --rcfile rust-sgx-gen/.pylintrc
    -
      name: test
      run: |
        pip install .
        cd example
        rust-sgx-gen -i input -o test -m 1 -e 5000 -r native
        cd test
        cargo check
    -
      name: publish
      if: ${{ github.event_name != 'pull_request' }}
      run: make upload PYPI_PASSWORD=${{ secrets.PYPI_TOKEN }}
